<?php
require_once __DIR__ . '/../../helpers/view_helper.php';
require_once __DIR__ . '/../../helpers/notify_helper.php';
require_once __DIR__ . '/../../config/db.php';
require_any_role(['admin','parent']);
$pageTitle='Fee Invoices';
$message='';$classId=(int)($_GET['class_id']??$_POST['class_id']??0);$term=(int)($_GET['term']??$_POST['term']??current_term());$year=(string)($_GET['academic_year']??$_POST['academic_year']??current_academic_year());$status=(string)($_GET['status']??'');
if($_SERVER['REQUEST_METHOD']==='POST' && get_current_role()==='admin'){verify_csrf();$stmt=$pdo->prepare('SELECT amount FROM fee_structures WHERE class_id=? AND term=? AND academic_year=?');$stmt->execute([$classId,$term,$year]);$amount=(float)$stmt->fetchColumn(); if($amount>0){$students=$pdo->prepare('SELECT student_id FROM students WHERE class_id=? AND is_active=1');$students->execute([$classId]);$ins=$pdo->prepare("INSERT INTO fee_invoices (student_id,term,academic_year,amount_due,amount_paid,balance,due_date,status) VALUES (?,?,?,?,0,?,DATE_ADD(CURDATE(), INTERVAL 30 DAY),'Unpaid') ON DUPLICATE KEY UPDATE amount_due=VALUES(amount_due), balance=GREATEST(0,VALUES(amount_due)-amount_paid), status=IF(GREATEST(0,VALUES(amount_due)-amount_paid)=0,'Paid',IF(amount_paid>0,'Partial','Unpaid'))"); foreach($students as $s){$ins->execute([(int)$s['student_id'],$term,$year,$amount,$amount]);}$message='Invoices generated.';}}
$over=$pdo->query("SELECT fi.*,s.full_name,u.user_id,u.email,u.full_name guardian_name FROM fee_invoices fi JOIN students s ON s.student_id=fi.student_id LEFT JOIN users u ON u.user_id=s.guardian_id WHERE fi.balance>0 AND fi.due_date<CURDATE()")->fetchAll(); foreach($over as $o){ if(!empty($o['user_id'])){$dup=$pdo->prepare("SELECT COUNT(*) FROM notifications WHERE recipient_id=? AND type='Fee Arrears' AND message LIKE ?");$dup->execute([(int)$o['user_id'],'%Term '.$o['term'].' '.$o['academic_year'].'%']); if((int)$dup->fetchColumn()===0){send_notification($pdo,(int)$o['user_id'],$o['email'],$o['guardian_name'],'Fee arrears',"Term {$o['term']} {$o['academic_year']} balance is ".money_fmt($o['balance']),'Fee Arrears');}}}
$sql='SELECT fi.*,s.full_name,s.admission_no,c.class_name FROM fee_invoices fi JOIN students s ON s.student_id=fi.student_id JOIN classes c ON c.class_id=s.class_id WHERE fi.term=? AND fi.academic_year=?';$params=[$term,$year]; if($classId){$sql.=' AND s.class_id=?';$params[]=$classId;} if($status!==''){$sql.=' AND fi.status=?';$params[]=$status;} if(get_current_role()==='parent'){$sql.=' AND s.guardian_id=?';$params[]=get_current_user_id();}$stmt=$pdo->prepare($sql.' ORDER BY s.full_name');$stmt->execute($params);$rows=$stmt->fetchAll();$classes=fetch_classes($pdo);
require __DIR__ . '/../../includes/header.php';
?>
<?php if($message): ?><div class="alert alert-success"><?= h($message) ?></div><?php endif; ?>
<?php if(get_current_role()==='admin'): ?><form method="post" class="card mb-3"><div class="card-body row g-2"><?= csrf_input() ?><div class="col-md-3"><select class="form-select" name="class_id"><?php foreach($classes as $c): ?><option value="<?= (int)$c['class_id'] ?>"<?= selected_attr($classId,$c['class_id']) ?>><?= h(class_label($c)) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><select class="form-select" name="term"><option<?= selected_attr($term,1) ?>>1</option><option<?= selected_attr($term,2) ?>>2</option><option<?= selected_attr($term,3) ?>>3</option></select></div><div class="col-md-2"><input class="form-control" name="academic_year" value="<?= h($year) ?>"></div><div class="col-md-3"><button class="btn btn-primary">Generate Invoices</button></div></div></form><?php endif; ?>
<form class="row g-2 mb-3 no-print"><div class="col-md-3"><select class="form-select" name="class_id"><option value="0">All classes</option><?php foreach($classes as $c): ?><option value="<?= (int)$c['class_id'] ?>"<?= selected_attr($classId,$c['class_id']) ?>><?= h(class_label($c)) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input class="form-control" name="academic_year" value="<?= h($year) ?>"></div><div class="col-md-2"><select class="form-select" name="term"><option<?= selected_attr($term,1) ?>>1</option><option<?= selected_attr($term,2) ?>>2</option><option<?= selected_attr($term,3) ?>>3</option></select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">Any status</option><option<?= selected_attr($status,'Unpaid') ?>>Unpaid</option><option<?= selected_attr($status,'Partial') ?>>Partial</option><option<?= selected_attr($status,'Paid') ?>>Paid</option></select></div><div class="col-md-2"><button class="btn btn-secondary">Filter</button></div></form>
<table class="table"><thead><tr><th>Student</th><th>Class</th><th>Due</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= h($r['admission_no'].' - '.$r['full_name']) ?></td><td><?= h($r['class_name']) ?></td><td><?= money_fmt($r['amount_due']) ?></td><td><?= money_fmt($r['amount_paid']) ?></td><td><?= money_fmt($r['balance']) ?></td><td><?= h($r['status']) ?></td></tr><?php endforeach; ?></tbody></table>
<?php require __DIR__ . '/../../includes/footer.php'; ?>
