<?php
require_once __DIR__ . '/../../helpers/view_helper.php';
require_once __DIR__ . '/../../helpers/receipt_helper.php';
require_once __DIR__ . '/../../helpers/notify_helper.php';
require_once __DIR__ . '/../../config/db.php';
require_role('admin');
$pageTitle='Record Payment';$q=trim((string)($_GET['q']??''));$invoiceId=(int)($_GET['invoice_id']??$_POST['invoice_id']??0);$error='';$matches=[];$invoice=null;
if($q!==''){$stmt=$pdo->prepare("SELECT fi.invoice_id,s.full_name,s.admission_no,fi.term,fi.academic_year,fi.balance FROM fee_invoices fi JOIN students s ON s.student_id=fi.student_id WHERE fi.balance>0 AND (s.full_name LIKE ? OR s.admission_no LIKE ?) ORDER BY s.full_name");$stmt->execute(["%{$q}%","%{$q}%"]);$matches=$stmt->fetchAll();}
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$amount=(float)$_POST['amount_paid'];$stmt=$pdo->prepare('SELECT fi.*,s.full_name,s.admission_no,u.user_id guardian_id,u.email guardian_email,u.full_name guardian_name FROM fee_invoices fi JOIN students s ON s.student_id=fi.student_id LEFT JOIN users u ON u.user_id=s.guardian_id WHERE fi.invoice_id=? FOR UPDATE');$pdo->beginTransaction();try{$stmt->execute([$invoiceId]);$invoice=$stmt->fetch();if(!$invoice||$amount<=0||$amount>(float)$invoice['balance']){throw new RuntimeException('Payment amount must be greater than zero and not exceed the balance.');}$insert=$pdo->prepare("INSERT INTO payments (invoice_id,amount_paid,payment_date,payment_method,receipt_no,recorded_by) VALUES (?,?,?,?, 'PENDING', ?)");$insert->execute([$invoiceId,$amount,$_POST['payment_date'],$_POST['payment_method'],get_current_user_id()]);$paymentId=(int)$pdo->lastInsertId();$receipt=generate_receipt_no($pdo,(int)$invoice['term'],$invoice['academic_year']);$pdo->prepare('UPDATE payments SET receipt_no=? WHERE payment_id=?')->execute([$receipt,$paymentId]);$newBalance=(float)$invoice['balance']-$amount;$status=$newBalance<=0?'Paid':'Partial';$pdo->prepare('UPDATE fee_invoices SET amount_paid=amount_paid+?, balance=?, status=? WHERE invoice_id=?')->execute([$amount,$newBalance,$status,$invoiceId]);$pdo->commit();if(!empty($invoice['guardian_id'])){send_notification($pdo,(int)$invoice['guardian_id'],$invoice['guardian_email'],$invoice['guardian_name'],'Payment received','Payment of '.money_fmt($amount).' received. Receipt '.$receipt,'Payment');}redirect('receipt.php?payment_id='.$paymentId);}catch(Throwable $e){$pdo->rollBack();$error=$e->getMessage();}}
if($invoiceId){$stmt=$pdo->prepare('SELECT fi.*,s.full_name,s.admission_no FROM fee_invoices fi JOIN students s ON s.student_id=fi.student_id WHERE fi.invoice_id=?');$stmt->execute([$invoiceId]);$invoice=$stmt->fetch();}
require __DIR__ . '/../../includes/header.php';
?>
<?php if($error): ?><div class="alert alert-danger"><?= h($error) ?></div><?php endif; ?>
<form class="row g-2 mb-3"><div class="col-md-8"><input class="form-control" name="q" value="<?= h($q) ?>" placeholder="Search student name or admission number"></div><div class="col-md-4"><button class="btn btn-primary">Search</button></div></form>
<?php if($matches): ?><div class="list-group mb-3"><?php foreach($matches as $m): ?><a class="list-group-item list-group-item-action" href="?invoice_id=<?= (int)$m['invoice_id'] ?>"><?= h($m['admission_no'].' - '.$m['full_name'].' Term '.$m['term'].' Balance '.money_fmt($m['balance'])) ?></a><?php endforeach; ?></div><?php endif; ?>
<?php if($invoice): ?><div class="card"><div class="card-body"><h2 class="h5"><?= h($invoice['admission_no'].' - '.$invoice['full_name']) ?></h2><p>Term <?= h($invoice['term']) ?> | Due <?= money_fmt($invoice['amount_due']) ?> | Paid <?= money_fmt($invoice['amount_paid']) ?> | Balance <?= money_fmt($invoice['balance']) ?></p><form method="post" class="row g-3"><?= csrf_input() ?><input type="hidden" name="invoice_id" value="<?= (int)$invoice['invoice_id'] ?>"><div class="col-md-3"><input class="form-control" data-max-balance="<?= h($invoice['balance']) ?>" type="number" step="0.01" min="0.01" max="<?= h($invoice['balance']) ?>" name="amount_paid" value="<?= h($invoice['balance']) ?>" required><div class="invalid-feedback">Invalid amount.</div></div><div class="col-md-3"><select class="form-select" name="payment_method"><option>Cash</option><option>Bank Transfer</option><option>Mobile Money</option><option>Cheque</option></select></div><div class="col-md-3"><input class="form-control" type="date" name="payment_date" value="<?= date('Y-m-d') ?>"></div><div class="col-md-3"><button class="btn btn-success">Record Payment</button></div></form></div></div><?php endif; ?>
<?php require __DIR__ . '/../../includes/footer.php'; ?>
