<?php
require_once __DIR__ . '/../../helpers/view_helper.php';
require_once __DIR__ . '/../../config/db.php';
require_any_role(['admin','parent']);
$pageTitle='Financial Reports';$classId=(int)($_GET['class_id']??0);$term=(int)($_GET['term']??current_term());$year=(string)($_GET['academic_year']??current_academic_year());$sql='SELECT s.full_name,s.admission_no,c.class_name,fi.amount_due,fi.amount_paid,fi.balance,fi.status FROM fee_invoices fi JOIN students s ON s.student_id=fi.student_id JOIN classes c ON c.class_id=s.class_id WHERE fi.term=? AND fi.academic_year=?';$params=[$term,$year]; if($classId){$sql.=' AND s.class_id=?';$params[]=$classId;} if(get_current_role()==='parent'){$sql.=' AND s.guardian_id=?';$params[]=get_current_user_id();}$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();$due=array_sum(array_column($rows,'amount_due'));$paid=array_sum(array_column($rows,'amount_paid'));$bal=array_sum(array_column($rows,'balance'));$classes=fetch_classes($pdo);require __DIR__ . '/../../includes/header.php';
?>
<form class="row g-2 mb-3 no-print"><div class="col-md-3"><select class="form-select" name="class_id"><option value="0">All classes</option><?php foreach($classes as $c): ?><option value="<?= (int)$c['class_id'] ?>"<?= selected_attr($classId,$c['class_id']) ?>><?= h(class_label($c)) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><select class="form-select" name="term"><option<?= selected_attr($term,1) ?>>1</option><option<?= selected_attr($term,2) ?>>2</option><option<?= selected_attr($term,3) ?>>3</option></select></div><div class="col-md-2"><input class="form-control" name="academic_year" value="<?= h($year) ?>"></div><div class="col-md-3"><button class="btn btn-primary">Filter</button> <button type="button" onclick="print()" class="btn btn-secondary">Print</button></div></form>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="card metric-card"><div class="card-body">Total Invoiced<div class="number"><?= money_fmt($due) ?></div></div></div></div><div class="col-md-4"><div class="card metric-card"><div class="card-body">Total Collected<div class="number"><?= money_fmt($paid) ?></div></div></div></div><div class="col-md-4"><div class="card metric-card"><div class="card-body">Outstanding<div class="number"><?= money_fmt($bal) ?></div></div></div></div></div>
<table class="table"><thead><tr><th>Student</th><th>Class</th><th>Invoiced</th><th>Paid</th><th>Balance</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td><?= h($r['admission_no'].' - '.$r['full_name']) ?></td><td><?= h($r['class_name']) ?></td><td><?= money_fmt($r['amount_due']) ?></td><td><?= money_fmt($r['amount_paid']) ?></td><td><?= money_fmt($r['balance']) ?></td><td><?= h($r['status']) ?></td></tr><?php endforeach; ?></tbody></table>
<?php require __DIR__ . '/../../includes/footer.php'; ?>
