<?php
require_once __DIR__ . '/../../helpers/view_helper.php';
require_once __DIR__ . '/../../helpers/notify_helper.php';
require_once __DIR__ . '/../../config/db.php';
require_role('admin');
$pageTitle='Send Announcement';$message=''; if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$target=$_POST['target'];$params=[]; if($target==='parents'){$sql="SELECT DISTINCT u.user_id,u.full_name,u.email FROM users u WHERE u.is_active=1 AND u.role='parent'";} elseif($target==='teachers'){$sql="SELECT DISTINCT u.user_id,u.full_name,u.email FROM users u WHERE u.is_active=1 AND u.role='teacher'";} elseif($target==='class'){$sql="SELECT DISTINCT u.user_id,u.full_name,u.email FROM users u JOIN students s ON s.guardian_id=u.user_id WHERE u.is_active=1 AND s.class_id=?";$params[]=(int)$_POST['class_id'];} else {$sql="SELECT DISTINCT u.user_id,u.full_name,u.email FROM users u WHERE 1=0";} $stmt=$pdo->prepare($sql);$stmt->execute($params);$count=0;foreach($stmt->fetchAll() as $u){send_notification($pdo,(int)$u['user_id'],$u['email'],$u['full_name'],trim((string)$_POST['subject']),trim((string)$_POST['body']),'Announcement');$count++;}$message="Announcement queued for {$count} recipient(s).";}$classes=fetch_classes($pdo);require __DIR__ . '/../../includes/header.php';
?>
<?php if($message): ?><div class="alert alert-success"><?= h($message) ?></div><?php endif; ?>
<form method="post" class="card"><div class="card-body row g-3"><?= csrf_input() ?><div class="col-md-4"><label class="form-label">Target</label><select class="form-select" name="target"><option value="parents">All Parents</option><option value="teachers">All Teachers</option><option value="class">Specific Class</option></select></div><div class="col-md-4"><label class="form-label">Class</label><select class="form-select" name="class_id"><?php foreach($classes as $c): ?><option value="<?= (int)$c['class_id'] ?>"><?= h($c['class_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-8"><label class="form-label">Subject</label><input class="form-control" name="subject" required></div><div class="col-12"><label class="form-label">Message</label><textarea class="form-control" rows="6" name="body" required></textarea></div><div class="col-12"><button class="btn btn-primary">Send</button></div></div></form>
<?php require __DIR__ . '/../../includes/footer.php'; ?>
