<?php
require_once __DIR__ . '/../../helpers/view_helper.php';
require_once __DIR__ . '/../../config/db.php';
require_any_role(['admin','parent','student']);
$pageTitle='Notification Log';$type=(string)($_GET['type']??'');$from=(string)($_GET['from']??'');$to=(string)($_GET['to']??'');$page=max(1,(int)($_GET['page']??1));$offset=($page-1)*20;$sql='SELECT n.*,u.full_name recipient FROM notifications n JOIN users u ON u.user_id=n.recipient_id WHERE 1=1';$params=[]; if(get_current_role()!=='admin'){$sql.=' AND n.recipient_id=?';$params[]=get_current_user_id();} if($type!==''){$sql.=' AND n.type=?';$params[]=$type;} if($from!==''){$sql.=' AND DATE(n.sent_at)>=?';$params[]=$from;} if($to!==''){$sql.=' AND DATE(n.sent_at)<=?';$params[]=$to;}$sql.=' ORDER BY n.sent_at DESC LIMIT 20 OFFSET '.$offset;$stmt=$pdo->prepare($sql);$stmt->execute($params);$rows=$stmt->fetchAll();require __DIR__ . '/../../includes/header.php';
?>
<form class="row g-2 mb-3 no-print"><div class="col-md-3"><select class="form-select" name="type"><option value="">All types</option><?php foreach(['Absence','Payment','Fee Arrears','Announcement','Disciplinary'] as $t): ?><option<?= selected_attr($type,$t) ?>><?= h($t) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><input class="form-control" type="date" name="from" value="<?= h($from) ?>"></div><div class="col-md-2"><input class="form-control" type="date" name="to" value="<?= h($to) ?>"></div><div class="col-md-2"><button class="btn btn-primary">Filter</button></div></form>
<table class="table"><thead><tr><th>#</th><th>Recipient</th><th>Type</th><th>Subject</th><th>Sent At</th><th>Status</th></tr></thead><tbody><?php foreach($rows as $i=>$r): ?><tr><td><?= $offset+$i+1 ?></td><td><?= h($r['recipient']) ?></td><td><?= h($r['type']) ?></td><td><?= h($r['subject']) ?></td><td><?= h($r['sent_at']) ?></td><td><span class="badge <?= $r['status']==='Sent'?'badge-pass':'badge-fail' ?>"><?= h($r['status']) ?></span></td></tr><?php endforeach; ?></tbody></table>
<a class="btn btn-sm btn-outline-secondary no-print" href="?page=<?= max(1,$page-1) ?>">Previous</a> <a class="btn btn-sm btn-outline-secondary no-print" href="?page=<?= $page+1 ?>">Next</a>
<?php require __DIR__ . '/../../includes/footer.php'; ?>
